[package]
name = "table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = {  git = "https://github.com/zesterer/chumsky" }
terminal-emoji = "0.4.1"
simple-error = "0.2.3"
ariadne = "0.1.5"